### ISSUE TITLE

Assistant not returning output

### ISSUE THREAD

**Issue by MadhavSharma08** [RohanDas28/Karen-A-Personal-Virtual-Assistant#2]
****Bro my assistant keeps listening and does not return output (maine harry bhai ka code copy kiya hai) and i have already installed pyaudio , so no issue with that also . It just wishes me and then it keeps on listening . PLZ HELP !!🙏🙏🙏****

**Comment by RohanDas28** [comment]
Can you share your code? Just make a repo .. I'll test and make sure that the program works fine. And for the listening part I think you may have messed up in the while loop. Just share your code so we can work it out bro ☺️.

**Comment by MadhavSharma08** [comment]
****Ok bro, will share in a while . And i do not want to listen music so i have not commanded the assistant to play music.****

**Comment by MadhavSharma08** [comment]
**I** HAVE CREATED A REPO AS 'JARVIS PERSONAL ASSISTANT' , YOU CAN CHECK THAT ****

**Comment by MadhavSharma08** [comment]
****AND` BRO I TRIED TO RUN YOUR CODE ALSO , THEN ALSO IT IS JUST LISTENING AND RETURNING NO OUTPUT . IS THERE A PROBLEM WITH MY LAPTOP ONLY ? PLZZZZ HELP :(****

**Comment by RohanDas28** [comment]
Okay I Am going to check there and I am closing This Issue Now 😉😊
